name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build for Linux
        run: go build -v -o go-home-or-away-linux ./...

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -v -o go-home-or-away-windows.exe ./...

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $(date +'%Y-%m-%d-%H-%M-%S') \
            --title "Release $(date +'%Y-%m-%d-%H-%M-%S')" \
            --notes "New release" \
            ./go-home-or-away-linux \
            ./go-home-or-away-windows.exe
